release-please-config.json

We want tags such as `v0.1.0`, and not `foreman-v0.1.0`.

chore: Remove package name from releases

---

.eslintrc.yml
backend/.eslintrc.yml
backend/package.json
frontend/.eslintrc.yml
frontend/package.json
package-lock.json
package.json

This patch adds ESLint linting based around the config that I personally maintain (`@meyfa/eslint-config`), which covers most of the requirements described in #18. For additional linting of frontend JSX code, the plugins `react`, `react-hooks`, and `jsx-a11y` (accessibility) are added and configured.
Closes #18

chore: Configure ESLint

---

.github/workflows/test.yml
backend/package.json
backend/test/util/mutex.test.ts
package-lock.json
package.json
test/config.test.ts

Closes #19. Mocha is used as the testing framework since the Node.js test runner doesn't have glob support in Node.js 20 and hence cannot be used with `*.ts` file extensions (without much effort). To make TypeScript work, including source mapping to ensure proper line numbers in error messages, tsx is used (ts-node seems to be no longer maintained).
This patch only adds very minimal tests, just ensuring the setup works.

chore: Set up unit testing

---

frontend/src/api/subscription.ts

Fixes #14. The subscription no longer resets when the interval changes, but only when the route or its arguments change.

fix: Avoid page flickering on pod completion

---

frontend/src/pages/Jobs.tsx

Fixes #11. The Jobs page would previously be completely empty (besides the heading) if there aren't any jobs. We now show a message there to inform the user that the emptiness is intentional, and that the page will refresh automatically once jobs arrive.
Error handling is also added to the page.

feat: Show a message when the job list is empty

---

README.md

Also removes `$` from code samples to allow the copy button to work, adds a set of links for quickly referencing other project locations, and a Contributing paragraph.

docs: Add README sections for Kubernetes and Docker installation

---

frontend/src/components/Card.tsx
frontend/src/components/InfoCard.tsx
frontend/src/components/JobPanel.tsx
frontend/src/components/Label.tsx
frontend/src/components/LinkCard.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Job.tsx
frontend/src/pages/Jobs.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Trigger.tsx

This patch removes repeated definitions of card-like components and introduces reusable `Card` and `LinkCard` components instead. There are no longer any cards with a border, however, `LinkCard` shows a border when hovering/focused (like `JobPanel` did previously).

feat: Use consistent design for card components

---

frontend/src/components/StatusDot.tsx
frontend/src/pages/Job.tsx

While the plain "dot" design might look good to people with full color vision, it is not at all accessible - e.g., people with red-green color blindness would find it difficult to distinguish success from failure.
This patch changes the success icon to an encircled checkmark, and the failure icon to an X-mark (without a circle), while keeping the "unknown" and "in progress" indicators the same since these are distinguishable by their animations.
The size is increased slightly to aid with visibility.

fix: Use distinct icons for "status dot"

---

backend/src/api/jobs.ts
backend/src/controllers/job.ts
backend/src/controllers/trigger.ts
backend/src/kubernetes/api.ts
backend/src/metadata.ts

In case the Renovate CronJob shares its namespace with other resources, we need to ensure that any jobs we return are actually related to the Renovate CronJob and not part of something else.
In the case of scheduled jobs, this is easily verified using the job's owner references. In the case of jobs triggered manually via Foreman, it appears we need to introduce a custom label by which we can then filter (which is what this patch does).
When testing this patch, non-related jobs no longer show up in Foreman while scheduled and manual jobs still do.

feat: Verify job ownership

---

backend/src/api/pod-logs.ts
backend/src/renovate/prettify-logs.ts
backend/test/renovate/prettify-logs.test.ts

This patch moves the `prettifyLogs` function (completely unchanged) to a separate file to simplify testing, and adds some test cases.

test: Add unit tests for prettifyLogs

---

backend/src/api/pod-progress.ts
backend/src/renovate/progress.ts
backend/test/renovate/progress.test.ts

This patch:
- moves progress extraction to a separate file
- replaces the config parameter with a more granular options parameter to simplify dependency injection
- removes completely unused `duration` property from interface `ProgressItem`
Finally, it adds unit tests for the extraction function.

fix: Refactor progress extraction and add tests

---

frontend/src/components/LogDialog.tsx

The log dialog is now always 90% of the screen height. Before, it would start out as 90% screen height while loading, but if the log text was extremely short, it would then jump to a much smaller height, which does not look good.

fix: Set fixed height for LogDialog

---

backend/src/api/cronjob.ts
backend/src/kubernetes/api.ts
frontend/src/components/InfoCard.tsx
frontend/src/components/Navigation.tsx
frontend/src/pages/Home.tsx

Before this patch, if the Renovate CronJob could not be found, we would return a 500 Internal Server Error and the UI would look broken. Now, we return a 404 Not Found, log a warning, and let the frontend show an error message component. The info cards are updated to properly handle this case.
Screenshot:

feat: Handle CronJob not found

---

backend/src/api/pod-progress.ts
frontend/src/pages/Job.tsx

When Renovate's autodiscovery turns up empty, for example when triggering a manual run with a non-existing repository scope, the log will not contain a list of matched repositories (not even an empty one). However, once the pod has completed, we know for a fact that no repositories are going to be discovered any more.
We can then show an empty list indicator, instead of continuing to show a loading indicator.
Screenshot:

feat: Handle empty repository autodiscovery

---

.github/pull_request_template.md

GitHub places the commit message at the beginning of the PR body, i.e., above the "Description" heading. This requires manual effort to cut and paste it to the proper location. If we remove the heading, the message is already at the proper location.
Fixes #(issue)
N/A

chore: Remove initial heading from PR template

---

backend/src/api/pod-logs.ts
backend/src/controllers/logs.ts

Pod logs are a major performance bottleneck, both due to enormous data transfers from the Kubernetes API and due to formatting being expensive. Before this patch, if multiple clients requested the same log simultaneously, these expensive operations were done multiple times in parallel. With this patch, mutexes are added around log retrieval and log formatting such that only one such operation can execute at any time.
In the multi-client scenario, the client arriving first will lock the mutex and retrieve the logs. When this client unlocks the mutex and another client is allowed through, the logs will already be cached and the request returns immediately.
Performance tests using the `ab` CLI tool confirm this: One of the requests still takes the same time as before, but all other requests …

fix: Serialize access to pod logs

---

backend/test/kubernetes/api.test.ts

For each test, we spin up a Fastify server with the endpoint that we expect to get called. If needed, the request body is checked, and the response is returned similar to a real Kubernetes API server. We then assert that the function under test behaved as expected.
There appears to be no way to perform these tests without a real HTTP server since `@kubernetes/client-node` doesn't seem to let us mock their HTTP client, but this may actually be a benefit, since we're dealing with the production code and not some mocked object.

test: Add tests for KubernetesApi

---

backend/test/auth/local-strategy.test.ts
backend/test/auth/oidc-strategy.test.ts

This patch adds tests for `makeLocalStrategy` and `makeOidcStrategy`.
N/A

test: Add tests for authentication strategies

---

Dockerfile
package.json
src/main.ts
src/server.ts

This patch adds handling of SIGINT and SIGTERM so that the server is closed gracefully. It also moves the code that starts the server into a function (in `server.ts`), separate from the command-line entrypoint (in newly-added `main.ts`). This way, each code part's responsibilities are clearer than if the process exit logic was conflated with running Fastify.
N/A

feat: Handle termination signals

---

integration/backend/trigger.test.ts
integration/fixtures.ts
integration/frontend.test.ts
package.json
tsconfig.lint.json

This patch adds the capability to perform integration testing of the entire server code, including frontend/backend, by making requests against instances started for each test case. Some initial tests are added to check static file serving and authentication of a backend route.
N/A

test: Set up integration testing

---

integration/backend/auth/local.test.ts
integration/backend/auth/logout.test.ts
integration/backend/auth/me.test.ts
integration/backend/auth/strategies.test.ts
integration/fixtures.ts

This patch tests the strategies, me, local login, and logout routes with our integration test suite. While adding these tests, some non-optimal server responses were discovered (such as returning errors as text instead of JSON, and using SameSite=Lax cookies instead of Strict), but these are completely non-critical and are annotated with TODO for now, to be fixed in a follow-up code change.
N/A

test: Add integration tests for local login

---

renovate.json

There are currently 5 open PRs by Renovate for updating dev dependency patch releases. To reduce review effort, group all of them together into a single PR (except semver-major updates).
Fixes #(issue)
N/A

chore: Group updates to devDependencies

---

backend/src/api/jobs.ts

When updating to TypeScript 5.6, it now (correctly) complains:
> src/api/jobs.ts(46,20): error TS2869: Right operand of ?? is
> unreachable because the left operand is never nullish.
Hence, the unreachable code is removed.
Fixes #(issue)
TypeScript PR: #102

fix: Remove unnecessary `??` operator

---

.gitignore
src/config.ts
test/config.test.ts

Foreman works when started with an empty config directory, but if it was missing entirely, the application would crash. This was never discovered because the Helm chart guarantees existence of the config directory.
A test is added to verify the fix.
Fixes #(issue)
N/A

fix: Avoid crash if run without config directory

---

renovate.json

This is meant to further reduce the number of PRs and review effort. Historically, `@types` updates have been very safe to merge overall and should not conflict when grouped this way.
Fixes #(issue)
N/A

chore: Include types in Renovate dev-deps group

---

renovate.json

Continuation of #95, adding a separate group for non-dev dependencies. There are 6 PRs currently that would be matched by the rule, which would greatly reduce maintenance effort, especially since we don't have to wait for each separate PR to be rebased before it can be merged.
N/A

chore: Group updates to dependencies

---

.dockerignore
.github/workflows/build.yml
.github/workflows/publish.yml
Dockerfile
README.md
backend/tsconfig.json
package.json
tsconfig.json

The image size is reduced by 13% using the following measures:
* Extended .dockerignore to remove further metadata and tests. This also ensures better layer caching for repeat builds.
* Cleaning npm cache for the final stage.
Inline source maps are enabled to improve error reporting. Stack traces will now refer to the TypeScript source locations instead of transpiled JS.
Multiplatform build for arm64 in addition to amd64 is enabled to improve performance on ARM devices due to not needing emulation.
Finally, the `docker run` example in README.md is amended to include security best practices.
N/A

feat: Optimize Docker image, build for amd64+arm64

---

.github/workflows/test.yml
package-lock.json
package.json

We already build the Docker image with Node.js 22. It makes sense to run the CI tests with the same version, and restrict non-containerized installations to v22 as well.
This is especially important since v22.12 added `require()` of ESM modules, which may greatly impact an application's run-time behaviour.
N/A

chore!: Require Node.js v22.12.0 or later

---

README.md
backend/src/auth/oidc-strategy.ts
backend/src/fastifyPassport.ts
backend/src/index.ts
backend/test/auth/oidc-strategy.test.ts
package-lock.json
package.json

BREAKING CHANGE: Foreman now requires the OIDC issuer to use HTTPS. Plain HTTP is no longer supported for OpenID Connect authentication.
Replaces #150
N/A

feat!: Update openid-client to v6, require HTTPS for issuer

---

backend/src/auth/oidc-strategy.ts

openid-client manipulates the redirect URI we gave based on the request URL, which will be wrong when behind a reverse proxy. This is a workaround for that based on upstream discussions.
Alternatively, it may be possible to configure the trust proxy setting, but this is a burden on users and not really necessary when we already have the URL and could use it as-is.

fix: Ensure proper OIDC redirect_uri is used
